/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

import (
	"time"
)

type ProcessEvent struct {

	Id int32 `json:"id,omitempty"`

	ProcessId string `json:"processId,omitempty"`

	Name string `json:"name,omitempty"`

	Log string `json:"log,omitempty"`

	Status string `json:"status,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}
